export const ROUTES = {
  Blank: `${process.env.PUBLIC_URL}/`,
  Login: `${process.env.PUBLIC_URL}/login`,
  JobSeekerRegistration: `${process.env.PUBLIC_URL}/jobseeker/registration`,
  JobSeekerDashboard: `${process.env.PUBLIC_URL}/jobseeker/dashboard`,
  JobSeekerJobs: `${process.env.PUBLIC_URL}/jobseeker/jobs`,
  JobSeekerProjects: `${process.env.PUBLIC_URL}/jobseeker/projects`,
  JobSeekerInbox: `${process.env.PUBLIC_URL}/jobseeker/inbox`,
  JobSeekerProfile: `${process.env.PUBLIC_URL}/jobseeker/profile`,
  RecruiterRegistration: `${process.env.PUBLIC_URL}/recruiter/registration`,
  RecruiterDashboard: `${process.env.PUBLIC_URL}/recruiter/dashboard`,
  RecruiterCandidates: `${process.env.PUBLIC_URL}/recruiter/candidates`,
  RecruiterJobs: `${process.env.PUBLIC_URL}/recruiter/jobs`,
  RecruiterReport: `${process.env.PUBLIC_URL}/recruiter/report`,
  RecruiterSchedule: `${process.env.PUBLIC_URL}/recruiter/schedule`,
  RecruiterApplicant: `${process.env.PUBLIC_URL}/recruiter/applicant`,
  RecruiterInbox: `${process.env.PUBLIC_URL}/recruiter/inbox`,
  RecruiterProfile: `${process.env.PUBLIC_URL}/recruiter/profile`,
  RecruiterDrag: `${process.env.PUBLIC_URL}/recruiter/drag`,
};
